/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Accounts {
  export type AccountStruct = {
    displayName: string;
    phoneNumber: string;
    email: string;
    isTenant: boolean;
    isActive: boolean;
    isActivated: boolean;
  };

  export type AccountStructOutput = [
    string,
    string,
    string,
    boolean,
    boolean,
    boolean
  ] & {
    displayName: string;
    phoneNumber: string;
    email: string;
    isTenant: boolean;
    isActive: boolean;
    isActivated: boolean;
  };
}

export interface AccountsInterface extends utils.Interface {
  contractName: "Accounts";
  functions: {
    "accounts(address)": FunctionFragment;
    "addAccount(string,string,string,bool,bool)": FunctionFragment;
    "addAdmin(address,string,string,string,bool,bool)": FunctionFragment;
    "admins(address)": FunctionFragment;
    "getAccount(address)": FunctionFragment;
    "getAdmin(address)": FunctionFragment;
    "getAffiliate(address)": FunctionFragment;
    "getNoAccount()": FunctionFragment;
    "kill()": FunctionFragment;
    "updateAccount(string,string,string)": FunctionFragment;
    "updateAdmin(address,string,string,string,bool)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "accounts", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addAccount",
    values: [string, string, string, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [string, string, string, string, boolean, boolean]
  ): string;
  encodeFunctionData(functionFragment: "admins", values: [string]): string;
  encodeFunctionData(functionFragment: "getAccount", values: [string]): string;
  encodeFunctionData(functionFragment: "getAdmin", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAffiliate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getNoAccount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "kill", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAccount",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAdmin",
    values: [string, string, string, string, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "accounts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addAccount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAccount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAffiliate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNoAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAdmin",
    data: BytesLike
  ): Result;

  events: {
    "AccountAdded(address)": EventFragment;
    "AccountUpdated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountUpdated"): EventFragment;
}

export type AccountAddedEvent = TypedEvent<[string], { user: string }>;

export type AccountAddedEventFilter = TypedEventFilter<AccountAddedEvent>;

export type AccountUpdatedEvent = TypedEvent<[string], { user: string }>;

export type AccountUpdatedEventFilter = TypedEventFilter<AccountUpdatedEvent>;

export interface Accounts extends BaseContract {
  contractName: "Accounts";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AccountsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, boolean, boolean, boolean] & {
        displayName: string;
        phoneNumber: string;
        email: string;
        isTenant: boolean;
        isActive: boolean;
        isActivated: boolean;
      }
    >;

    addAccount(
      displayName: string,
      email: string,
      phoneNumber: string,
      _isTenant: boolean,
      isActivated: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addAdmin(
      _address: string,
      displayName: string,
      email: string,
      phoneNumber: string,
      _isTenant: boolean,
      isActivated: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    admins(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string] & { affiliate: string }>;

    getAccount(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[Accounts.AccountStructOutput]>;

    getAdmin(_address: string, overrides?: CallOverrides): Promise<[string]>;

    getAffiliate(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getNoAccount(overrides?: CallOverrides): Promise<[string]>;

    kill(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateAccount(
      displayName: string,
      email: string,
      phoneNumber: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateAdmin(
      _address: string,
      displayName: string,
      email: string,
      phoneNumber: string,
      isActive: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  accounts(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, boolean, boolean, boolean] & {
      displayName: string;
      phoneNumber: string;
      email: string;
      isTenant: boolean;
      isActive: boolean;
      isActivated: boolean;
    }
  >;

  addAccount(
    displayName: string,
    email: string,
    phoneNumber: string,
    _isTenant: boolean,
    isActivated: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addAdmin(
    _address: string,
    displayName: string,
    email: string,
    phoneNumber: string,
    _isTenant: boolean,
    isActivated: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  admins(arg0: string, overrides?: CallOverrides): Promise<string>;

  getAccount(
    _address: string,
    overrides?: CallOverrides
  ): Promise<Accounts.AccountStructOutput>;

  getAdmin(_address: string, overrides?: CallOverrides): Promise<string>;

  getAffiliate(_address: string, overrides?: CallOverrides): Promise<string>;

  getNoAccount(overrides?: CallOverrides): Promise<string>;

  kill(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateAccount(
    displayName: string,
    email: string,
    phoneNumber: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateAdmin(
    _address: string,
    displayName: string,
    email: string,
    phoneNumber: string,
    isActive: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, boolean, boolean, boolean] & {
        displayName: string;
        phoneNumber: string;
        email: string;
        isTenant: boolean;
        isActive: boolean;
        isActivated: boolean;
      }
    >;

    addAccount(
      displayName: string,
      email: string,
      phoneNumber: string,
      _isTenant: boolean,
      isActivated: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addAdmin(
      _address: string,
      displayName: string,
      email: string,
      phoneNumber: string,
      _isTenant: boolean,
      isActivated: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    admins(arg0: string, overrides?: CallOverrides): Promise<string>;

    getAccount(
      _address: string,
      overrides?: CallOverrides
    ): Promise<Accounts.AccountStructOutput>;

    getAdmin(_address: string, overrides?: CallOverrides): Promise<string>;

    getAffiliate(_address: string, overrides?: CallOverrides): Promise<string>;

    getNoAccount(overrides?: CallOverrides): Promise<string>;

    kill(overrides?: CallOverrides): Promise<void>;

    updateAccount(
      displayName: string,
      email: string,
      phoneNumber: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateAdmin(
      _address: string,
      displayName: string,
      email: string,
      phoneNumber: string,
      isActive: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AccountAdded(address)"(user?: null): AccountAddedEventFilter;
    AccountAdded(user?: null): AccountAddedEventFilter;

    "AccountUpdated(address)"(user?: null): AccountUpdatedEventFilter;
    AccountUpdated(user?: null): AccountUpdatedEventFilter;
  };

  estimateGas: {
    accounts(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    addAccount(
      displayName: string,
      email: string,
      phoneNumber: string,
      _isTenant: boolean,
      isActivated: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addAdmin(
      _address: string,
      displayName: string,
      email: string,
      phoneNumber: string,
      _isTenant: boolean,
      isActivated: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    admins(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAccount(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAdmin(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAffiliate(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNoAccount(overrides?: CallOverrides): Promise<BigNumber>;

    kill(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateAccount(
      displayName: string,
      email: string,
      phoneNumber: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateAdmin(
      _address: string,
      displayName: string,
      email: string,
      phoneNumber: string,
      isActive: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAccount(
      displayName: string,
      email: string,
      phoneNumber: string,
      _isTenant: boolean,
      isActivated: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addAdmin(
      _address: string,
      displayName: string,
      email: string,
      phoneNumber: string,
      _isTenant: boolean,
      isActivated: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    admins(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccount(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAdmin(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAffiliate(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNoAccount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    kill(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateAccount(
      displayName: string,
      email: string,
      phoneNumber: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateAdmin(
      _address: string,
      displayName: string,
      email: string,
      phoneNumber: string,
      isActive: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
