/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Documents {
  export type DocumentStruct = {
    requester: string;
    verifier: string;
    certifier: string;
    name: string;
    description: string;
    docAddress: string;
    fee: BigNumberish;
    status: BigNumberish;
  };

  export type DocumentStructOutput = [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    number
  ] & {
    requester: string;
    verifier: string;
    certifier: string;
    name: string;
    description: string;
    docAddress: string;
    fee: BigNumber;
    status: number;
  };
}

export interface DocumentsInterface extends utils.Interface {
  contractName: "Documents";
  functions: {
    "accountsAddress()": FunctionFragment;
    "addDocument(address,address,string,string,string,uint256)": FunctionFragment;
    "balances(address)": FunctionFragment;
    "certifyDocument(string,uint256,uint8)": FunctionFragment;
    "getCounts(address)": FunctionFragment;
    "getDocument(string,uint256)": FunctionFragment;
    "getDocuments()": FunctionFragment;
    "kill()": FunctionFragment;
    "verifyDocument(string,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accountsAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDocument",
    values: [string, string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balances", values: [string]): string;
  encodeFunctionData(
    functionFragment: "certifyDocument",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getCounts", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getDocument",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocuments",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "kill", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountsAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "certifyDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCounts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocuments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;

  events: {
    "DocumentAdded(address)": EventFragment;
    "DocumentCertified(address)": EventFragment;
    "DocumentRejected(address)": EventFragment;
    "DocumentVerified(address)": EventFragment;
    "Test(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DocumentAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DocumentCertified"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DocumentRejected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DocumentVerified"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Test"): EventFragment;
}

export type DocumentAddedEvent = TypedEvent<[string], { user: string }>;

export type DocumentAddedEventFilter = TypedEventFilter<DocumentAddedEvent>;

export type DocumentCertifiedEvent = TypedEvent<[string], { user: string }>;

export type DocumentCertifiedEventFilter =
  TypedEventFilter<DocumentCertifiedEvent>;

export type DocumentRejectedEvent = TypedEvent<[string], { user: string }>;

export type DocumentRejectedEventFilter =
  TypedEventFilter<DocumentRejectedEvent>;

export type DocumentVerifiedEvent = TypedEvent<[string], { user: string }>;

export type DocumentVerifiedEventFilter =
  TypedEventFilter<DocumentVerifiedEvent>;

export type TestEvent = TypedEvent<[BigNumber], { test: BigNumber }>;

export type TestEventFilter = TypedEventFilter<TestEvent>;

export interface Documents extends BaseContract {
  contractName: "Documents";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DocumentsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accountsAddress(overrides?: CallOverrides): Promise<[string]>;

    addDocument(
      _verifier: string,
      _certifier: string,
      _name: string,
      _description: string,
      _docAddress: string,
      _fee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    balances(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    certifyDocument(
      _docAddress: string,
      _fee: BigNumberish,
      status: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCounts(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        pending: BigNumber;
        certified: BigNumber;
        verified: BigNumber;
        rejected: BigNumber;
        total: BigNumber;
      }
    >;

    getDocument(
      docAddress: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [Documents.DocumentStructOutput] & {
        _document: Documents.DocumentStructOutput;
      }
    >;

    getDocuments(
      overrides?: CallOverrides
    ): Promise<
      [Documents.DocumentStructOutput[]] & {
        _documents: Documents.DocumentStructOutput[];
      }
    >;

    kill(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verifyDocument(
      docAddress: string,
      status: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  accountsAddress(overrides?: CallOverrides): Promise<string>;

  addDocument(
    _verifier: string,
    _certifier: string,
    _name: string,
    _description: string,
    _docAddress: string,
    _fee: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  certifyDocument(
    _docAddress: string,
    _fee: BigNumberish,
    status: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCounts(
    _address: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      pending: BigNumber;
      certified: BigNumber;
      verified: BigNumber;
      rejected: BigNumber;
      total: BigNumber;
    }
  >;

  getDocument(
    docAddress: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Documents.DocumentStructOutput>;

  getDocuments(
    overrides?: CallOverrides
  ): Promise<Documents.DocumentStructOutput[]>;

  kill(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verifyDocument(
    docAddress: string,
    status: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accountsAddress(overrides?: CallOverrides): Promise<string>;

    addDocument(
      _verifier: string,
      _certifier: string,
      _name: string,
      _description: string,
      _docAddress: string,
      _fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    certifyDocument(
      _docAddress: string,
      _fee: BigNumberish,
      status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getCounts(
      _address: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        pending: BigNumber;
        certified: BigNumber;
        verified: BigNumber;
        rejected: BigNumber;
        total: BigNumber;
      }
    >;

    getDocument(
      docAddress: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Documents.DocumentStructOutput>;

    getDocuments(
      overrides?: CallOverrides
    ): Promise<Documents.DocumentStructOutput[]>;

    kill(overrides?: CallOverrides): Promise<void>;

    verifyDocument(
      docAddress: string,
      status: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DocumentAdded(address)"(user?: null): DocumentAddedEventFilter;
    DocumentAdded(user?: null): DocumentAddedEventFilter;

    "DocumentCertified(address)"(user?: null): DocumentCertifiedEventFilter;
    DocumentCertified(user?: null): DocumentCertifiedEventFilter;

    "DocumentRejected(address)"(user?: null): DocumentRejectedEventFilter;
    DocumentRejected(user?: null): DocumentRejectedEventFilter;

    "DocumentVerified(address)"(user?: null): DocumentVerifiedEventFilter;
    DocumentVerified(user?: null): DocumentVerifiedEventFilter;

    "Test(uint256)"(test?: null): TestEventFilter;
    Test(test?: null): TestEventFilter;
  };

  estimateGas: {
    accountsAddress(overrides?: CallOverrides): Promise<BigNumber>;

    addDocument(
      _verifier: string,
      _certifier: string,
      _name: string,
      _description: string,
      _docAddress: string,
      _fee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    certifyDocument(
      _docAddress: string,
      _fee: BigNumberish,
      status: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCounts(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    getDocument(
      docAddress: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDocuments(overrides?: CallOverrides): Promise<BigNumber>;

    kill(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verifyDocument(
      docAddress: string,
      status: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accountsAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addDocument(
      _verifier: string,
      _certifier: string,
      _name: string,
      _description: string,
      _docAddress: string,
      _fee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    certifyDocument(
      _docAddress: string,
      _fee: BigNumberish,
      status: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCounts(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDocument(
      docAddress: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDocuments(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    kill(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verifyDocument(
      docAddress: string,
      status: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
