/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Services {
  export type FeeStruct = { name: string; cost: BigNumberish };

  export type FeeStructOutput = [string, BigNumber] & {
    name: string;
    cost: BigNumber;
  };
}

export interface ServicesInterface extends utils.Interface {
  contractName: "Services";
  functions: {
    "accountsAddress()": FunctionFragment;
    "addFee(string,uint256)": FunctionFragment;
    "deleteFee(uint256)": FunctionFragment;
    "getFee(uint256)": FunctionFragment;
    "getFees(address)": FunctionFragment;
    "kill()": FunctionFragment;
    "updateFee(string,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accountsAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addFee",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getFees", values: [string]): string;
  encodeFunctionData(functionFragment: "kill", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateFee",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountsAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deleteFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kill", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateFee", data: BytesLike): Result;

  events: {
    "FeeAdded(address)": EventFragment;
    "FeeDeleted(address)": EventFragment;
    "FeeUpdated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FeeAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeUpdated"): EventFragment;
}

export type FeeAddedEvent = TypedEvent<[string], { user: string }>;

export type FeeAddedEventFilter = TypedEventFilter<FeeAddedEvent>;

export type FeeDeletedEvent = TypedEvent<[string], { user: string }>;

export type FeeDeletedEventFilter = TypedEventFilter<FeeDeletedEvent>;

export type FeeUpdatedEvent = TypedEvent<[string], { user: string }>;

export type FeeUpdatedEventFilter = TypedEventFilter<FeeUpdatedEvent>;

export interface Services extends BaseContract {
  contractName: "Services";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ServicesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accountsAddress(overrides?: CallOverrides): Promise<[string]>;

    addFee(
      name: string,
      cost: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteFee(
      _index: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getFee(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Services.FeeStructOutput] & { fee: Services.FeeStructOutput }>;

    getFees(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[Services.FeeStructOutput[]]>;

    kill(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateFee(
      name: string,
      cost: BigNumberish,
      _index: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  accountsAddress(overrides?: CallOverrides): Promise<string>;

  addFee(
    name: string,
    cost: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteFee(
    _index: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getFee(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Services.FeeStructOutput>;

  getFees(
    _address: string,
    overrides?: CallOverrides
  ): Promise<Services.FeeStructOutput[]>;

  kill(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateFee(
    name: string,
    cost: BigNumberish,
    _index: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accountsAddress(overrides?: CallOverrides): Promise<string>;

    addFee(
      name: string,
      cost: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deleteFee(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getFee(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Services.FeeStructOutput>;

    getFees(
      _address: string,
      overrides?: CallOverrides
    ): Promise<Services.FeeStructOutput[]>;

    kill(overrides?: CallOverrides): Promise<void>;

    updateFee(
      name: string,
      cost: BigNumberish,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "FeeAdded(address)"(user?: null): FeeAddedEventFilter;
    FeeAdded(user?: null): FeeAddedEventFilter;

    "FeeDeleted(address)"(user?: null): FeeDeletedEventFilter;
    FeeDeleted(user?: null): FeeDeletedEventFilter;

    "FeeUpdated(address)"(user?: null): FeeUpdatedEventFilter;
    FeeUpdated(user?: null): FeeUpdatedEventFilter;
  };

  estimateGas: {
    accountsAddress(overrides?: CallOverrides): Promise<BigNumber>;

    addFee(
      name: string,
      cost: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteFee(
      _index: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getFee(_index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getFees(_address: string, overrides?: CallOverrides): Promise<BigNumber>;

    kill(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateFee(
      name: string,
      cost: BigNumberish,
      _index: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accountsAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addFee(
      name: string,
      cost: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteFee(
      _index: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getFee(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFees(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    kill(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateFee(
      name: string,
      cost: BigNumberish,
      _index: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
