/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface StringUtilsInterface extends utils.Interface {
  contractName: "StringUtils";
  functions: {
    "compare(string,string)": FunctionFragment;
    "equal(string,string)": FunctionFragment;
    "indexOf(string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "compare",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "equal",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "indexOf",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "compare", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "equal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "indexOf", data: BytesLike): Result;

  events: {};
}

export interface StringUtils extends BaseContract {
  contractName: "StringUtils";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StringUtilsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    compare(
      _a: string,
      _b: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    equal(
      _a: string,
      _b: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    indexOf(
      _haystack: string,
      _needle: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  compare(
    _a: string,
    _b: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  equal(_a: string, _b: string, overrides?: CallOverrides): Promise<boolean>;

  indexOf(
    _haystack: string,
    _needle: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    compare(
      _a: string,
      _b: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    equal(_a: string, _b: string, overrides?: CallOverrides): Promise<boolean>;

    indexOf(
      _haystack: string,
      _needle: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    compare(
      _a: string,
      _b: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    equal(
      _a: string,
      _b: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    indexOf(
      _haystack: string,
      _needle: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    compare(
      _a: string,
      _b: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    equal(
      _a: string,
      _b: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    indexOf(
      _haystack: string,
      _needle: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
